# Export/Import Configuration
# docker-compose exec strapi bash
# strapi configuration:dump -f dump.json
# strapi configuration:restore -f dump.json
version: "3"
services:
  strapi:
    image: naskio/strapi
    platform: linux/amd64
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ./app:/srv/app 
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
  postgres:
    restart: always
    image: postgres:15-alpine
    container_name: postgres-strapi
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data